# Generated by Django 4.1.3 on 2023-07-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientunits',
            name='recipe_unit',
            field=models.CharField(default='test', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientunits',
            name='recipe_amt',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
