# Generated by Django 4.1.3 on 2023-08-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0003_alter_ingredientunits_i_name_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationingredients',
            name='si_station_num',
            field=models.ForeignKey(db_column='si_station_num', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='station_ings', to='fftracker.stations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientunits',
            name='i_unit_id',
            field=models.AutoField(db_column='i_unit_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationingredients',
            name='si_ing',
            field=models.ForeignKey(db_column='si_ing_id', on_delete=django.db.models.deletion.CASCADE, to='fftracker.ingredientnames'),
        ),
    ]
