# Generated by Django 4.1.3 on 2023-08-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0004_stationingredients_si_station_num_and_more'),
    ]

    operations = [
    ]
