# Generated by Django 4.1.3 on 2023-08-13 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0005_alter_ingredientunits_i_name_id'),
    ]

    operations = [
    ]
