# Generated by Django 4.1.3 on 2023-08-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0006_remove_ingredientunits_i_name_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationingredients',
            name='si_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationingredients',
            name='si_station_num',
            field=models.ForeignKey(db_column='si_station_num', on_delete=django.db.models.deletion.CASCADE, related_name='stn_ings', to='fftracker.stations'),
        ),
    ]
