# Generated by Django 4.1.3 on 2023-08-13 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0007_alter_stationingredients_si_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientunits',
            name='i_name_id',
        ),
        migrations.RemoveField(
            model_name='stationingredients',
            name='si_ing',
        ),
        migrations.AddField(
            model_name='ingredientunits',
            name='i_name',
            field=models.ForeignKey(db_column='i_name_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ing_units', to='fftracker.ingredientnames'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stationingredients',
            name='si_ing_name',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
