# Generated by Django 4.1.3 on 2023-09-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0009_remove_stationingredients_si_ing_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationingredients',
            name='si_recipe_ing',
            field=models.CharField(db_column='si_recipe_ing', max_length=50),
        ),
    ]
