# Generated by Django 4.1.3 on 2023-11-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0010_alter_stationingredients_si_recipe_ing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingTypes',
            fields=[
                ('pkg_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('pkg_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingTypeSizes',
            fields=[
                ('pkg_size_id', models.AutoField(primary_key=True, serialize=False)),
                ('pkg_size', models.CharField(max_length=50)),
                ('pkg_holds', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
    ]
