# Generated by Django 4.1.3 on 2023-11-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0012_packagingtypesizes_pkg_type_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagingtypes',
            name='pkg_type_id',
        ),
        migrations.AlterField(
            model_name='packagingtypes',
            name='pkg_type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
