# Generated by Django 4.1.3 on 2023-11-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0013_remove_packagingtypes_pkg_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagingtypes',
            name='pkg_type_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagingtypes',
            name='pkg_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
