# Generated by Django 4.1.3 on 2023-12-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0014_packagingtypes_pkg_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='r_servings',
            field=models.SmallIntegerField(default=1),
        ),
    ]
