# Generated by Django 4.1.3 on 2023-12-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0015_recipes_r_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='r_servings',
            field=models.SmallIntegerField(default='1'),
        ),
    ]
