# Generated by Django 4.1.3 on 2024-02-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0017_alter_ingredientunits_recipe_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientunits',
            name='recipe_amt',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='ingredientunits',
            name='shop_amt',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
