# Generated by Django 4.1.3 on 2024-03-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0019_households_hh_bags_or_crates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='households',
            name='hh_bags_or_crates',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
