# Generated by Django 4.1.3 on 2025-01-15 16:35

from django.db import migrations, models
import django.db.models.deletion
import fftracker.models


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0022_recipes_r_card_upload_recipes_r_img_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="households",
            name="childrenSnacks_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="households",
            name="foodBox_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="households",
            name="ppMealKit_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="households",
            name="rteMeal_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="imageupload",
            name="file",
            field=models.FileField(
                storage=fftracker.models.OverwriteAzureStorage, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="r_card_upload",
            field=models.ForeignKey(
                blank=True,
                db_column="r_card_upload",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="r_card",
                to="fftracker.imageupload",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="r_img_upload",
            field=models.ForeignKey(
                blank=True,
                db_column="r_img_upload",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="r_image",
                to="fftracker.imageupload",
            ),
        ),
    ]
