# Generated by Django 4.1.3 on 2025-01-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0023_households_childrensnacks_flag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="households",
            name="childrenSnacks_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="households",
            name="foodBox_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="households",
            name="ppMealKit_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="households",
            name="rteMeal_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
