# Generated by Django 4.1.3 on 2025-01-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0024_households_childrensnacks_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="households",
            name="childrenSnacks_timestamp",
        ),
        migrations.RemoveField(
            model_name="households",
            name="foodBox_timestamp",
        ),
        migrations.RemoveField(
            model_name="households",
            name="ppMealKit_timestamp",
        ),
        migrations.RemoveField(
            model_name="households",
            name="rteMeal_timestamp",
        ),
        migrations.AddField(
            model_name="households",
            name="childrenSnacks_timestamps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="households",
            name="foodBox_timestamps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="households",
            name="ppMealKit_timestamps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="households",
            name="rteMeal_timestamps",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
