# Generated by Django 4.1.3 on 2025-01-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0025_remove_households_childrensnacks_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="households",
            name="childrenSnacks_timestamps",
        ),
        migrations.RemoveField(
            model_name="households",
            name="foodBox_timestamps",
        ),
        migrations.RemoveField(
            model_name="households",
            name="ppMealKit_timestamps",
        ),
        migrations.RemoveField(
            model_name="households",
            name="rteMeal_timestamps",
        ),
        migrations.CreateModel(
            name="ProductSubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.CharField(max_length=30)),
                ("subscribed", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_history",
                        to="fftracker.households",
                    ),
                ),
            ],
            options={
                "db_table": "product_subscription_history",
                "managed": True,
            },
        ),
    ]
