# Generated by Django 4.1.3 on 2025-01-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0026_remove_households_childrensnacks_timestamps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="households",
            name="ebt",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="productsubscriptionhistory",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
