# Generated by Django 4.1.3 on 2025-04-01 00:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0026_remove_households_childrensnacks_timestamps_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsubscriptionhistory",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
