# Generated by Django 4.1.3 on 2025-03-24 13:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0026_remove_households_childrensnacks_timestamps_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_servings", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "servings",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="households",
            name="ebt",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="households",
            name="ebt_refill_date",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="households",
            name="restriction_flag",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="ingredients",
            name="parent_category",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ingredients",
            name="specific_category",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productsubscriptionhistory",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="PausedDates",
            fields=[
                (
                    "paused_date_id",
                    models.SmallAutoField(primary_key=True, serialize=False),
                ),
                ("pause_start_date", models.DateField()),
                ("pause_end_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "hh_id",
                    models.ForeignKey(
                        db_column="hh_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paused_dates",
                        to="fftracker.households",
                    ),
                ),
            ],
            options={
                "db_table": "paused_dates",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="IngredientConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_a", models.SmallIntegerField(default=0)),
                ("unit_b", models.SmallIntegerField(default=0)),
                ("amt_a", models.DecimalField(decimal_places=2, max_digits=5)),
                ("amt_b", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "ingredientId",
                    models.ForeignKey(
                        db_column="ingredientId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_conversion",
                        to="fftracker.ingredients",
                    ),
                ),
            ],
            options={
                "db_table": "ingredient_conversion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DietaryRestrictions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("restriction_type", models.CharField(max_length=50)),
                ("servings", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dietary_restrictions",
                        to="fftracker.households",
                    ),
                ),
            ],
            options={
                "db_table": "dietary_restrictions",
                "managed": True,
            },
        ),
    ]
