# Generated by Django 4.1.3 on 2025-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0027_households_ebt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="households",
            name="ebt_refill_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
