# Generated by Django 4.1.3 on 2025-04-01 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0027_servings_households_ebt_households_ebt_refill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='households',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
