# Generated by Django 4.1.3 on 2025-03-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fftracker",
            "0027_servings_households_ebt_households_ebt_refill_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredients",
            name="parent_category",
            field=models.SmallIntegerField(
                choices=[
                    (0, "NoCategory"),
                    (1, "Fruits"),
                    (2, "Vegetables"),
                    (3, "Dairy"),
                    (4, "Protein"),
                    (5, "Grains"),
                    (6, "Specialty"),
                    (7, "Condiments"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="specific_category",
            field=models.SmallIntegerField(
                choices=[
                    (0, "NoCategory"),
                    (1, "Melons"),
                    (2, "Berries"),
                    (3, "OtherFruits"),
                    (4, "DarkgreenVegetables"),
                    (5, "RedOrangeVegetables"),
                    (6, "StarchyVegetables"),
                    (7, "BeansPeasLentils"),
                    (8, "OtherVegetables"),
                    (9, "Milk"),
                    (10, "Cheese"),
                    (11, "Yogurt"),
                    (12, "NonDairyCalciumAlternatives"),
                    (13, "Meats"),
                    (14, "Poultry"),
                    (15, "Seafood"),
                    (16, "Eggs"),
                    (17, "NutsSeeds"),
                    (18, "BeansPeasLentilsProtein"),
                    (19, "WholeGrains"),
                    (20, "RefinedGrains"),
                    (21, "GlutenFree"),
                    (22, "Vegan"),
                    (23, "Allergies"),
                    (24, "Sauces"),
                    (25, "Seasonings"),
                    (26, "Broths"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="servings",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
