# Generated by Django 4.1.3 on 2025-04-01 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0028_servings_households_ebt_households_ebt_refill_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_servings', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'servings',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='households',
            name='ebt',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='households',
            name='ebt_refill_date',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='households',
            name='restriction_flag',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='parent_category',
            field=models.SmallIntegerField(choices=[(0, 'NoCategory'), (1, 'Fruits'), (2, 'Vegetables'), (3, 'Dairy'), (4, 'Protein'), (5, 'Grains'), (6, 'Specialty'), (7, 'Condiments')], default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='specific_category',
            field=models.SmallIntegerField(choices=[(0, 'NoCategory'), (1, 'Melons'), (2, 'Berries'), (3, 'OtherFruits'), (4, 'DarkgreenVegetables'), (5, 'RedOrangeVegetables'), (6, 'StarchyVegetables'), (7, 'BeansPeasLentils'), (8, 'OtherVegetables'), (9, 'Milk'), (10, 'Cheese'), (11, 'Yogurt'), (12, 'NonDairyCalciumAlternatives'), (13, 'Meats'), (14, 'Poultry'), (15, 'Seafood'), (16, 'Eggs'), (17, 'NutsSeeds'), (18, 'BeansPeasLentilsProtein'), (19, 'WholeGrains'), (20, 'RefinedGrains'), (21, 'GlutenFree'), (22, 'Vegan'), (23, 'Allergies'), (24, 'Sauces'), (25, 'Seasonings'), (26, 'Broths')], default=0),
        ),
        migrations.CreateModel(
            name='PausedDates',
            fields=[
                ('paused_date_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('pause_start_date', models.DateField()),
                ('pause_end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('hh_id', models.ForeignKey(db_column='hh_id', on_delete=django.db.models.deletion.CASCADE, related_name='paused_dates', to='fftracker.households')),
            ],
            options={
                'db_table': 'paused_dates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IngredientConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_a', models.SmallIntegerField(default=0)),
                ('unit_b', models.SmallIntegerField(default=0)),
                ('amt_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amt_b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingredientId', models.ForeignKey(db_column='ingredientId', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_conversion', to='fftracker.ingredients')),
            ],
            options={
                'db_table': 'ingredient_conversion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DietaryRestrictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('restriction_type', models.CharField(max_length=50)),
                ('servings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_restrictions', to='fftracker.households')),
            ],
            options={
                'db_table': 'dietary_restrictions',
                'managed': True,
            },
        ),
    ]
