# Generated by Django 4.1.3 on 2025-01-29 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0028_households_ebt_refill_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="households",
            name="ebt_refill_date",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
    ]
