# Generated by Django 4.1.3 on 2025-04-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "fftracker",
            "0029_servings_households_ebt_households_ebt_refill_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeinstructions",
            name="step_inst",
        ),
        migrations.RemoveField(
            model_name="recipeinstructions",
            name="step_no",
        ),
        migrations.RemoveField(
            model_name="recipeinstructions",
            name="stn_name",
        ),
        migrations.RemoveField(
            model_name="stations",
            name="stn_recipe_num",
        ),
        migrations.AddField(
            model_name="recipeinstructions",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="recipeinstructions",
            name="instruction_type",
            field=models.CharField(
                choices=[("prep", "Preparation"), ("cook", "Cooking")],
                default="prep",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recipeinstructions",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipeinstructions",
            name="step_num",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="recipeinstructions",
            name="time_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipeinstructions",
            name="inst_recipe_num",
            field=models.ForeignKey(
                db_column="inst_recipe_num",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r_instructions",
                to="fftracker.recipes",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="m_s",
            field=models.SmallIntegerField(
                choices=[(0, "Snack"), (1, "Meal"), (2, "Sauce/Dip")]
            ),
        ),
    ]
