# Generated by Django 4.1.3 on 2025-04-21 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0030_remove_recipeinstructions_step_inst_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeinstructions",
            name="time_minutes",
        ),
        migrations.AddField(
            model_name="recipeinstructions",
            name="amount_per_serving",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="recipeinstructions",
            name="substeps",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipeinstructions",
            name="unit",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name="recipeinstructions",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="recipeinstructions",
            name="inst_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recipeinstructions",
            name="inst_recipe_num",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r_instructions",
                to="fftracker.recipes",
            ),
        ),
        migrations.AlterField(
            model_name="recipeinstructions",
            name="instruction_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="recipeinstructions",
            name="step_num",
            field=models.IntegerField(),
        ),
    ]
