# Generated by Django 4.1.3 on 2025-04-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0031_remove_recipeinstructions_time_minutes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredients",
            name="prep",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="recipeingredients",
            name="ri_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="r_num",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
