# Generated by Django 4.1.3 on 2025-03-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0036_ingredientcategory_ingredientcategorynew_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientcategorynew',
            table='ingredient_category_new',
        ),
        migrations.AlterModelTable(
            name='ingredientnew',
            table='ingredient_new',
        ),
        migrations.AlterModelTable(
            name='ingredientsubcategorynew',
            table='ingredient_subcategory_new',
        ),
    ]
