# Generated by Django 4.1.3 on 2025-03-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0037_alter_ingredientcategorynew_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientCategory',
        ),
    ]
