# Generated by Django 4.1.3 on 2025-03-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0038_delete_ingredientcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ingredientcategorynew',
            table='ingredient_category',
        ),
    ]
