# Generated by Django 4.1.3 on 2025-03-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0039_alter_ingredientcategorynew_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.CharField(choices=[('Fruits', 0), ('Vegetables', 1), ('Dairy', 2), ('Protein', 3), ('Grains', 4), ('Specialty', 5), ('Condiments', 6)], max_length=50)),
                ('specific_category', models.CharField(choices=[('Melons', 0), ('Berries', 1), ('OtherFruits', 2), ('DarkgreenVegetables', 3), ('RedOrangeVegetables', 4), ('StarchyVegetables', 5), ('BeansPeasLentils', 6), ('OtherVegetables', 7), ('Milk', 8), ('Cheese', 9), ('Yogurt', 10), ('NonDairyCalciumAlternatives', 11), ('Meats', 12), ('Poultry', 13), ('Seafood', 14), ('Eggs', 15), ('NutsSeeds', 16), ('BeansPeasLentilsProtein', 17), ('WholeGrains', 18), ('RefinedGrains', 19), ('GlutenFree', 20), ('Vegan', 21), ('Allergies', 22), ('Sauces', 23), ('Seasonings', 24), ('Broths', 25)], max_length=50)),
            ],
            options={
                'db_table': 'ingredient_category',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='IngredientNEW',
            new_name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientCategoryNEW',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
        migrations.AlterModelTable(
            name='ingredientsubcategory',
            table='ingredient_subcategory',
        ),
        migrations.RenameModel(
            old_name='IngredientSubCategoryNEW',
            new_name='IngredientSubCategory',
        ),
        migrations.AlterField(
            model_name='ingredientsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fftracker.ingredientcategory'),
        ),
    ]
