FROM --platform=linux/amd64 node:20.5.1 AS build
WORKDIR /ffreact


COPY . /ffreact/package.json ./
COPY . /ffreact ./

RUN npm install

RUN npm run build

FROM nginx:1.18.0-alpine

COPY ./webserver/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /ffreact/build /usr/share/nginx/html