# Build Django
FROM --platform=linux/amd64 python:3.11.4-bullseye

# Enable real-time terminal logs for build process
ENV PYTHONUNBUFFERED=1
# Set the working directory to /ffdjango
WORKDIR /
ADD ./fftracker/requirements.txt ./fftracker/requirements.txt

# Install dependencies and gunicorn
RUN pip install -r fftracker/requirements.txt
RUN pip install gunicorn

# Add all files from /ffdjango to the container's /ffdjango
ADD . /

# Copy the gunicorn bash startup script to the docker entrypoint script location in the container
COPY entrypoint.sh /docker-entrypoint.d/
# Allow read/write access in the container
RUN chmod +x /docker-entrypoint.d/entrypoint.sh
# Expose port 8080 on docker container
EXPOSE 8000:8000
# Have docker use our custom entrypoint script
ENTRYPOINT [ "/docker-entrypoint.d/entrypoint.sh" ]