FROM  python:3.11.4-bullseye

ENV PYTHONUNBUFFERED=1

WORKDIR /ffdjango/fftracker

ADD . /ffdjango/

RUN pip install -r requirements.txt

RUN echo hello

# copy from the current directory of the Dockerfile to /ffdjango in the image

EXPOSE 8000

CMD ["python", "manage.py", "runserver"]