FROM --platform=linux/amd64 python:3.11.4-bullseye

ENV PYTHONUNBUFFERED=1

WORKDIR /ffdjango/fftracker

ADD . /ffdjango/

RUN pip install -r requirements.txt
RUN pip install gunicorn

COPY entrypoint.sh /docker-entrypoint.d/

RUN chmod +x /docker-entrypoint.d/entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.d/entrypoint.sh" ]